CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  hash BYTEA NOT NULL
);

CREATE TABLE model {
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  provider TEXT NOT NULL UNIQUE,
  config BYTEA NOT NULL
}